apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virustotal-exporter.fullname" . }}
  labels:
    {{- include "virustotal-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  VIRUSTOTAL_API_KEY: {{ required "secrets.virustotalApiKey is required" .Values.secrets.virustotalApiKey | quote }}
  {{- with .Values.secrets.cloudflareApiToken }}
  CLOUDFLARE_API_TOKEN: {{ . | quote }}
  {{- end }}
